#! /bin/bash 
sudo ifdown wlan0
sudo mv /etc/network/interfaces /etc/network/interfaces.baaaak
sudo cp /etc/network/interfaces.apmode /etc/network/interfaces
sudo ifup wlan0
sudo killall hostapd
sudo service isc-dhcp-server restart
sudo /usr/sbin/hostapd -B /etc/hostapd/hostapd.conf 
echo finish
